/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.eanghel.planning.ui.internal.PlanningActivator;

public class PlanningUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PlanningActivator.getInstance().getInjector("uk.ac.kcl.eanghel.planning.Planning");
	}

}
