/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.eanghel.planning.parser.antlr.internal.InternalPlanningParser;
import uk.ac.kcl.eanghel.planning.services.PlanningGrammarAccess;

public class PlanningParser extends AbstractAntlrParser {

	@Inject
	private PlanningGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPlanningParser createParser(XtextTokenStream stream) {
		return new InternalPlanningParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TaskPlanning";
	}

	public PlanningGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PlanningGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
