/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.eanghel.planning.PlanningRuntimeModule;
import uk.ac.kcl.eanghel.planning.PlanningStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PlanningIdeSetup extends PlanningStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PlanningRuntimeModule(), new PlanningIdeModule()));
	}
	
}
