/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.ide;


/**
 * Use this class to register ide components.
 */
public class PlanningIdeModule extends AbstractPlanningIdeModule {
}
