/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.planning.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.eanghel.planning.planning.FeatureTask;
import uk.ac.kcl.eanghel.planning.planning.PlanningPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Feature Task</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.impl.FeatureTaskImpl#getFeat <em>Feat</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FeatureTaskImpl extends TaskTypeImpl implements FeatureTask
{
  /**
   * The default value of the '{@link #getFeat() <em>Feat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeat()
   * @generated
   * @ordered
   */
  protected static final String FEAT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFeat() <em>Feat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeat()
   * @generated
   * @ordered
   */
  protected String feat = FEAT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FeatureTaskImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PlanningPackage.Literals.FEATURE_TASK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFeat()
  {
    return feat;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFeat(String newFeat)
  {
    String oldFeat = feat;
    feat = newFeat;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PlanningPackage.FEATURE_TASK__FEAT, oldFeat, feat));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PlanningPackage.FEATURE_TASK__FEAT:
        return getFeat();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PlanningPackage.FEATURE_TASK__FEAT:
        setFeat((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PlanningPackage.FEATURE_TASK__FEAT:
        setFeat(FEAT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PlanningPackage.FEATURE_TASK__FEAT:
        return FEAT_EDEFAULT == null ? feat != null : !FEAT_EDEFAULT.equals(feat);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (feat: ");
    result.append(feat);
    result.append(')');
    return result.toString();
  }

} //FeatureTaskImpl
