/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.planning.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uk.ac.kcl.eanghel.planning.planning.Owner;
import uk.ac.kcl.eanghel.planning.planning.PlanningPackage;
import uk.ac.kcl.eanghel.planning.planning.Project;
import uk.ac.kcl.eanghel.planning.planning.TaskPlanning;
import uk.ac.kcl.eanghel.planning.planning.Tasks;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Task Planning</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.impl.TaskPlanningImpl#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.impl.TaskPlanningImpl#getOwners <em>Owners</em>}</li>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.impl.TaskPlanningImpl#getProjs <em>Projs</em>}</li>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.impl.TaskPlanningImpl#getTasks <em>Tasks</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TaskPlanningImpl extends MinimalEObjectImpl.Container implements TaskPlanning
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getOwners() <em>Owners</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwners()
   * @generated
   * @ordered
   */
  protected EList<Owner> owners;

  /**
   * The cached value of the '{@link #getProjs() <em>Projs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProjs()
   * @generated
   * @ordered
   */
  protected EList<Project> projs;

  /**
   * The cached value of the '{@link #getTasks() <em>Tasks</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTasks()
   * @generated
   * @ordered
   */
  protected EList<Tasks> tasks;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TaskPlanningImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PlanningPackage.Literals.TASK_PLANNING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PlanningPackage.TASK_PLANNING__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Owner> getOwners()
  {
    if (owners == null)
    {
      owners = new EObjectContainmentEList<Owner>(Owner.class, this, PlanningPackage.TASK_PLANNING__OWNERS);
    }
    return owners;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Project> getProjs()
  {
    if (projs == null)
    {
      projs = new EObjectContainmentEList<Project>(Project.class, this, PlanningPackage.TASK_PLANNING__PROJS);
    }
    return projs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Tasks> getTasks()
  {
    if (tasks == null)
    {
      tasks = new EObjectContainmentEList<Tasks>(Tasks.class, this, PlanningPackage.TASK_PLANNING__TASKS);
    }
    return tasks;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PlanningPackage.TASK_PLANNING__OWNERS:
        return ((InternalEList<?>)getOwners()).basicRemove(otherEnd, msgs);
      case PlanningPackage.TASK_PLANNING__PROJS:
        return ((InternalEList<?>)getProjs()).basicRemove(otherEnd, msgs);
      case PlanningPackage.TASK_PLANNING__TASKS:
        return ((InternalEList<?>)getTasks()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PlanningPackage.TASK_PLANNING__NAME:
        return getName();
      case PlanningPackage.TASK_PLANNING__OWNERS:
        return getOwners();
      case PlanningPackage.TASK_PLANNING__PROJS:
        return getProjs();
      case PlanningPackage.TASK_PLANNING__TASKS:
        return getTasks();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PlanningPackage.TASK_PLANNING__NAME:
        setName((String)newValue);
        return;
      case PlanningPackage.TASK_PLANNING__OWNERS:
        getOwners().clear();
        getOwners().addAll((Collection<? extends Owner>)newValue);
        return;
      case PlanningPackage.TASK_PLANNING__PROJS:
        getProjs().clear();
        getProjs().addAll((Collection<? extends Project>)newValue);
        return;
      case PlanningPackage.TASK_PLANNING__TASKS:
        getTasks().clear();
        getTasks().addAll((Collection<? extends Tasks>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PlanningPackage.TASK_PLANNING__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PlanningPackage.TASK_PLANNING__OWNERS:
        getOwners().clear();
        return;
      case PlanningPackage.TASK_PLANNING__PROJS:
        getProjs().clear();
        return;
      case PlanningPackage.TASK_PLANNING__TASKS:
        getTasks().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PlanningPackage.TASK_PLANNING__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PlanningPackage.TASK_PLANNING__OWNERS:
        return owners != null && !owners.isEmpty();
      case PlanningPackage.TASK_PLANNING__PROJS:
        return projs != null && !projs.isEmpty();
      case PlanningPackage.TASK_PLANNING__TASKS:
        return tasks != null && !tasks.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //TaskPlanningImpl
