/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.planning;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Analyse Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.AnalyseTask#getAnalyse <em>Analyse</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getAnalyseTask()
 * @model
 * @generated
 */
public interface AnalyseTask extends TaskType
{
  /**
   * Returns the value of the '<em><b>Analyse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Analyse</em>' attribute.
   * @see #setAnalyse(String)
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getAnalyseTask_Analyse()
   * @model
   * @generated
   */
  String getAnalyse();

  /**
   * Sets the value of the '{@link uk.ac.kcl.eanghel.planning.planning.AnalyseTask#getAnalyse <em>Analyse</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Analyse</em>' attribute.
   * @see #getAnalyse()
   * @generated
   */
  void setAnalyse(String value);

} // AnalyseTask
