/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.planning;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bug Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.BugTask#getBug <em>Bug</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getBugTask()
 * @model
 * @generated
 */
public interface BugTask extends TaskType
{
  /**
   * Returns the value of the '<em><b>Bug</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bug</em>' attribute.
   * @see #setBug(String)
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getBugTask_Bug()
   * @model
   * @generated
   */
  String getBug();

  /**
   * Sets the value of the '{@link uk.ac.kcl.eanghel.planning.planning.BugTask#getBug <em>Bug</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bug</em>' attribute.
   * @see #getBug()
   * @generated
   */
  void setBug(String value);

} // BugTask
