/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.planning;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Deploy Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.DeployTask#getDeploy <em>Deploy</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getDeployTask()
 * @model
 * @generated
 */
public interface DeployTask extends TaskType
{
  /**
   * Returns the value of the '<em><b>Deploy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Deploy</em>' attribute.
   * @see #setDeploy(String)
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getDeployTask_Deploy()
   * @model
   * @generated
   */
  String getDeploy();

  /**
   * Sets the value of the '{@link uk.ac.kcl.eanghel.planning.planning.DeployTask#getDeploy <em>Deploy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Deploy</em>' attribute.
   * @see #getDeploy()
   * @generated
   */
  void setDeploy(String value);

} // DeployTask
