/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.planning;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.FeatureTask#getFeat <em>Feat</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getFeatureTask()
 * @model
 * @generated
 */
public interface FeatureTask extends TaskType
{
  /**
   * Returns the value of the '<em><b>Feat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feat</em>' attribute.
   * @see #setFeat(String)
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getFeatureTask_Feat()
   * @model
   * @generated
   */
  String getFeat();

  /**
   * Sets the value of the '{@link uk.ac.kcl.eanghel.planning.planning.FeatureTask#getFeat <em>Feat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feat</em>' attribute.
   * @see #getFeat()
   * @generated
   */
  void setFeat(String value);

} // FeatureTask
