/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.planning;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tasks</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.Tasks#getTaskType <em>Task Type</em>}</li>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.Tasks#getOwner <em>Owner</em>}</li>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.Tasks#getPriority <em>Priority</em>}</li>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.Tasks#getPoints <em>Points</em>}</li>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.Tasks#getStatus <em>Status</em>}</li>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.Tasks#getProj <em>Proj</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTasks()
 * @model
 * @generated
 */
public interface Tasks extends EObject
{
  /**
   * Returns the value of the '<em><b>Task Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Task Type</em>' containment reference.
   * @see #setTaskType(TaskType)
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTasks_TaskType()
   * @model containment="true"
   * @generated
   */
  TaskType getTaskType();

  /**
   * Sets the value of the '{@link uk.ac.kcl.eanghel.planning.planning.Tasks#getTaskType <em>Task Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Task Type</em>' containment reference.
   * @see #getTaskType()
   * @generated
   */
  void setTaskType(TaskType value);

  /**
   * Returns the value of the '<em><b>Owner</b></em>' reference list.
   * The list contents are of type {@link uk.ac.kcl.eanghel.planning.planning.Owner}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owner</em>' reference list.
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTasks_Owner()
   * @model
   * @generated
   */
  EList<Owner> getOwner();

  /**
   * Returns the value of the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priority</em>' attribute.
   * @see #setPriority(int)
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTasks_Priority()
   * @model
   * @generated
   */
  int getPriority();

  /**
   * Sets the value of the '{@link uk.ac.kcl.eanghel.planning.planning.Tasks#getPriority <em>Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Priority</em>' attribute.
   * @see #getPriority()
   * @generated
   */
  void setPriority(int value);

  /**
   * Returns the value of the '<em><b>Points</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' containment reference.
   * @see #setPoints(Points)
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTasks_Points()
   * @model containment="true"
   * @generated
   */
  Points getPoints();

  /**
   * Sets the value of the '{@link uk.ac.kcl.eanghel.planning.planning.Tasks#getPoints <em>Points</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Points</em>' containment reference.
   * @see #getPoints()
   * @generated
   */
  void setPoints(Points value);

  /**
   * Returns the value of the '<em><b>Status</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.eanghel.planning.planning.Status}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' attribute.
   * @see uk.ac.kcl.eanghel.planning.planning.Status
   * @see #setStatus(Status)
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTasks_Status()
   * @model
   * @generated
   */
  Status getStatus();

  /**
   * Sets the value of the '{@link uk.ac.kcl.eanghel.planning.planning.Tasks#getStatus <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' attribute.
   * @see uk.ac.kcl.eanghel.planning.planning.Status
   * @see #getStatus()
   * @generated
   */
  void setStatus(Status value);

  /**
   * Returns the value of the '<em><b>Proj</b></em>' reference list.
   * The list contents are of type {@link uk.ac.kcl.eanghel.planning.planning.Project}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proj</em>' reference list.
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTasks_Proj()
   * @model
   * @generated
   */
  EList<Project> getProj();

} // Tasks
