/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.planning;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTaskType()
 * @model
 * @generated
 */
public interface TaskType extends EObject
{
} // TaskType
