/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.planning;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task Planning</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.TaskPlanning#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.TaskPlanning#getOwners <em>Owners</em>}</li>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.TaskPlanning#getProjs <em>Projs</em>}</li>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.TaskPlanning#getTasks <em>Tasks</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTaskPlanning()
 * @model
 * @generated
 */
public interface TaskPlanning extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTaskPlanning_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.eanghel.planning.planning.TaskPlanning#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Owners</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.eanghel.planning.planning.Owner}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owners</em>' containment reference list.
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTaskPlanning_Owners()
   * @model containment="true"
   * @generated
   */
  EList<Owner> getOwners();

  /**
   * Returns the value of the '<em><b>Projs</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.eanghel.planning.planning.Project}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projs</em>' containment reference list.
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTaskPlanning_Projs()
   * @model containment="true"
   * @generated
   */
  EList<Project> getProjs();

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.eanghel.planning.planning.Tasks}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTaskPlanning_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<Tasks> getTasks();

} // TaskPlanning
