/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.planning;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.eanghel.planning.planning.TestTask#getTest <em>Test</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTestTask()
 * @model
 * @generated
 */
public interface TestTask extends TaskType
{
  /**
   * Returns the value of the '<em><b>Test</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test</em>' attribute.
   * @see #setTest(String)
   * @see uk.ac.kcl.eanghel.planning.planning.PlanningPackage#getTestTask_Test()
   * @model
   * @generated
   */
  String getTest();

  /**
   * Sets the value of the '{@link uk.ac.kcl.eanghel.planning.planning.TestTask#getTest <em>Test</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Test</em>' attribute.
   * @see #getTest()
   * @generated
   */
  void setTest(String value);

} // TestTask
