/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPlanningScopeProvider extends DelegatingScopeProvider {
}
