/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PlanningUiModule extends AbstractPlanningUiModule {

	public PlanningUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
