/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PlanningStandaloneSetup extends PlanningStandaloneSetupGenerated {

	public static void doSetup() {
		new PlanningStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
