/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PlanningRuntimeModule extends AbstractPlanningRuntimeModule {
}
