/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class PlanningOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
