/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractPlanningValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(uk.ac.kcl.eanghel.planning.planning.PlanningPackage.eINSTANCE);
		return result;
	}
}
