/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.eanghel.planning.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.eanghel.planning.ui.internal.PlanningActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PlanningExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(PlanningActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		PlanningActivator activator = PlanningActivator.getInstance();
		return activator != null ? activator.getInjector(PlanningActivator.UK_AC_KCL_EANGHEL_PLANNING_PLANNING) : null;
	}

}
